### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aliakbar7013** [nafishahmeddev/fintracker#1]
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///C:/Users/mohda/Flutter%20Projects/expense%20trackeer/fintracker/lib/model/account.model.dart:35:11
  - file:///C:/Users/mohda/Flutter%20Projects/expense%20trackeer/fintracker/lib/model/category.model.dart:23:11
Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.

**Comment by shafisma** [comment]
Run the command with --no-tree-shake-icons. The command will be flutter build apk --no-tree-shake-icons
