### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by Sarthak0101130** [nafishahmeddev/fintracker#3]
Because month_year_picker 0.3.0+1 depends on intl ^0.18.0 and no versions of month_year_picker match >0.3.0+1 <0.4.0, month_year_picker ^0.3.0+1 requires intl ^0.18.0.
So, because fintracker depends on both intl ^0.19.0 and month_year_picker ^0.3.0+1, version solving failed.

if i changed it to intl ^0.18.0 error comes !!!

Because fintracker depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because fintracker depends on intl ^0.18.1, version solving failed.

How to Resolve it ?

**Comment by Sarthak0101130** [comment]
The build APK failed !

This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///D:/fintracker-master/lib/model/account.model.dart:35:11
  - file:///D:/fintracker-master/lib/model/category.model.dart:23:11
Target aot_android_asset_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
FAILURE: Build failed with an exception.

**Comment by Sarthak0101130** [comment]
Sorry Not resolved

**Comment by nafishahmeddev** [comment]
I'm working on it.

**Comment by nafishahmeddev** [comment]
For run

flutter run --release --no-tree-shake-icons

For Android build

flutter build apk --release --no-tree-shake-icons

For iOS build

flutter build ipa --release --no-tree-shake-icons
