### ISSUE TITLE
Can the project roadmap be added to the Readme.md file?

### ISSUE THREAD

**Issue by ndubbaka** [nafishahmeddev/fintracker#5]
Please add project roadmap to the Readme.md file.

**Comment by nafishahmeddev** [comment]
We have published our roadmap for an upcoming feature, which can be accessed here: https://github.com/nafishahmeddev/fintracker/blob/master/roadmap.md

**Comment by nafishahmeddev** [comment]
Hi nikhil we have added roadmap for the upcoming feature. Thanks for your
effort.
